ALTER TYPE "ProductStatus" ADD VALUE IF NOT EXISTS 'REJECTED';

ALTER TABLE "Customer"
ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "blocked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "blockReason" TEXT;

ALTER TABLE "Artisan"
ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "blocked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "rejectionReason" TEXT,
ADD COLUMN "blockReason" TEXT;

ALTER TABLE "Admin"
ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Category"
ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Product"
ADD COLUMN "rejectionReason" TEXT;

ALTER TABLE "Review"
ADD COLUMN "hidden" BOOLEAN NOT NULL DEFAULT false;
